version: '3'
services:
  app:
    build:
      context: .
    tty: true
    volumes:
      - ./source:/app
    environment:
      WATCHPACK_POLLING: true
      NEXT_PUBLIC_ENV: "dev"
    # command: sh -c "[ -f ~/.exec-once ] || { yarn install && touch ~/.exec-once; } && yarn build && yarn start"
    command: sh -c "[ -f ~/.exec-once ] || { yarn install && touch ~/.exec-once; } && yarn dev"
    ports:
      - "3000:3000"