name: marge prd

on: 
  push:
    branches:
      - main
      
env:
  TARGET_REPO: blog
jobs:
  release:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name:  push tag
        id: version
        uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          WITH_V: true

      - name: git merge
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          git pull origin prd
          git checkout -b prd
          git merge main --no-commit --no-ff
          git checkout HEAD -- source/contents
          git commit -m "Merge main"
          git push --set-upstream origin prd