name: marge prd

on: 
  push:
    branches:
      - main
      
env:
  TARGET_REPO: blog

jobs:
  release:
    runs-on: ubuntu-latest
    steps: 
      - id: create
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          repositories: ${{ env.TARGET_REPO }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name:  push tag
        id: version
        uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          WITH_V: true

      - name: git merge
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          git checkout prd
          git merge main --no-commit --no-ff
          git checkout HEAD -- source/contents
          git commit -m "Merge main"

      - name: Push changes to target repository
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ steps.create.outputs.token }} 
          repository: laininthewired/${{ env.TARGET_REPO }} 
          branch: prd
          directory: ${{ env.TARGET_REPO }} 