name: marge prd

on: 
  push:
    branches:
      - main
      
env:
  TARGET_REPO: blog
jobs:
  release:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - id: create
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          repositories: ${{ env.TARGET_REPO }}

      - name:  push tag
        id: version
        uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          WITH_V: true

      - name: git merge
        env:
          GITHUB_APP_TOKEN: ${{ steps.create.outputs.token }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          git checkout prd
          git merge main --no-commit --no-ff
          git checkout HEAD -- source/contents
          git commit -m "Merge main"
          git push --set-upstream https://x-access-token:${GITHUB_APP_TOKEN}@github.com:LainInTheWired/blog.git prd
